version: '3.6'

services:
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  redis:
    image: 'redis:6.2'
    ports:
      - 6379:6379
    command: >
      --requirepass Admin123
  postgres-db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verysecret
      - POSTGRES_DB=postgres-db
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9090"
  minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc mb myminio/file-storage; /usr/bin/mc policy set public myminio/file-storage; exit 0; "
